apiVersion: batch/v1
kind: Job
metadata:
  name: delete-ark-config
  namespace: {{ .Values.namespace.backup.name }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "2"
spec:
  template:
    metadata:
      name: delete-ark-config
      namespace: {{ .Values.namespace.backup.name }}
    spec:
      restartPolicy: Never
      containers:
        - name: delete-ark-config
          image: claranet/gcloud-kubectl-docker:latest
          imagePullPolicy: Always
          command: ["kubectl","delete","-f","/tmp/"]
          volumeMounts:
            - name: ark-server-config
              mountPath: /tmp
      volumes:
        - name: ark-server-config
          configMap:
            name: ark-server-config
      serviceAccountName: {{ template "ark-server.hookSA" . }}
