apiVersion: batch/v1
kind: Job
metadata:
  name: delete-ark-backups
  namespace: {{ .Values.namespace.backup.name }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
spec:
  template:
    metadata:
      name: delete-ark-backups
      namespace: {{ .Values.namespace.backup.name }}
    spec:
      restartPolicy: Never
      containers:
        - name: delete-ark-backups
          image: claranet/gcloud-kubectl-docker
          imagePullPolicy: Always
          command: ["kubectl", "delete", "-n", {{ .Values.namespace.backup.name | quote }}, "backup", "--all"]
          volumeMounts:
            - name: ark-server-config
              mountPath: /tmp
      volumes:
        - name: ark-server-config
          configMap:
            name: ark-server-config
      serviceAccountName: {{ template "ark-server.hookSA" . }}
